### ISSUE TITLE
Cannot install module "sale_adapt_price_wizard" Odoo 12 (out of the box)

### ISSUE THREAD

**Issue by YannickLevadoux** [beescoop/Obeesdoo#530]
Hello 

Running Odoo 12 (out of the box, docker image `odoo:12.0`) on a docker container, I did not manage to install module "sale_adapt_price_wizard".
I put the all content of the branch v12 from https://github.com/beescoop/Obeesdoo onto the addon folder for the container
Error message I've got is related to a not found external dependancy : `No module named openupgradelib`

Seeing this error message I I tried to install the openupgradelib python package inside the container `pip3 install openupgradelib`

Now I have this error : 

```
Erreur:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 967, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 955, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-62>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 75, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 446, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 562, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 179, in load_module_graph
    load_openerp_module(package.name)
  File "/usr/lib/python3/dist-packages/odoo/modules/module.py", line 368, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/usr/lib/python3/dist-packages/odoo/modules/module.py", line 82, in load_module
    exec(open(modfile, 'rb').read(), new_mod.__dict__)
  File "<string>", line 5, in <module>
  File "/var/lib/odoo/.local/lib/python3.5/site-packages/openupgradelib/openupgrade.py", line 48, in <module>
    from psycopg2 import sql
ImportError: cannot import name 'sql'
```

Am I doing something wrong ? 
Any idea how to solve this out ?

**Comment by robinkeunen** [comment]
Hi Yannick,

The requirements.txt does not pin the version of openupgradelib (bad practice, we should fix that) so I guess there is a discrepancy between the dependencies of the version of openupgradelib you installed and the version of psycopg2 present on your docker image.

It works locally with this _pip freeze_ :

```
...
openupgradelib==3.4.0
...
psycopg2==2.9.6
psycopg2-binary==2.9.4
...
```

The full freeze : 
```
aniso8601==7.0.0
apispec==6.0.0
Babel==2.3.4
bcrypt==4.0.1
beautifulsoup4==4.11.1
cachetools==5.2.0
cairocffi==1.4.0
CairoSVG==2.6.0
Cerberus==1.3.4
certifi==2022.9.24
cffi==1.15.1
cfgv==3.3.1
chardet==3.0.4
click==8.1.3
click-odoo==1.6.0
click-odoo-contrib==1.16.1
cryptography==38.0.1
cssselect==1.2.0
cssselect2==0.7.0
decorator==4.0.10
defusedxml==0.7.1
distlib==0.3.6
docutils==0.12
ebaysdk==2.1.5
filelock==3.8.0
freezegun==1.2.2
gevent==1.5.0
graphene==2.1.9
graphql-core==2.3.2
graphql-relay==2.0.1
graphql-server-core==2.0.0
greenlet==0.4.14
html2text==2016.9.19
identify==2.5.8
idna==2.7
importlib-metadata==5.0.0
importlib-resources==5.12.0
Jinja2==2.10.1
jsondiff==2.0.0
Levenshtein==0.20.7
libsass==0.12.3
lxml==4.2.3
Mako==1.0.4
manifestoo_core==0.11.0
MarkupSafe==0.23
marshmallow==3.18.0
marshmallow-objects==2.3.0
mock==2.0.0
mollie-api-python==2.2.3
nodeenv==1.7.0
num2words==0.5.6
oauthlib==3.2.2
-e git+ssh://git@github.com/coopiteasy/OCB@2da5e58172a6f282d8d86f158f219b771682a75d#egg=odoo
odoo-repl==0.0.3
ofxparse==0.16
openupgradelib==3.4.0
packaging==21.3
paramiko==2.11.0
parse-accept-language==0.1.2
passlib==1.6.5
pbr==5.10.0
phonenumbers==8.10.19
Pillow==6.1.0
platformdirs==2.5.2
pre-commit==2.21.0
promise==2.3
psutil==4.3.1
psycopg2==2.9.6
psycopg2-binary==2.9.4
pycoda==1.1.0
pycparser==2.21
pydot==1.2.3
Pygments==2.15.1
pyldap==2.4.28
PyNaCl==1.5.0
pyparsing==2.1.10
PyPDF2==1.26.0
pypng==0.20220715.0
PyQRCode==1.2.1
pyquerystring==1.1
pyserial==3.1.1
python-barcode==0.12.0
python-dateutil==2.8.2
python-Levenshtein==0.20.7
python-stdnum==1.17
pytz==2016.7
pyusb==1.0.0
PyYAML==6.0
qrcode==5.3
rapidfuzz==2.11.1
reportlab==3.3.0
requests==2.20.0
requests-oauthlib==1.3.1
Rx==1.6.1
six==1.16.0
soupsieve==2.3.2.post1
suds-jurko==0.6
tinycss2==1.2.1
toml==0.10.2
typing_extensions==4.4.0
Unidecode==1.3.6
urllib3==1.24.3
vatnumber==1.2
virtualenv==20.16.6
vobject==0.9.3
webencodings==0.5.1
Werkzeug==0.11.15
xlrd==1.0.0
XlsxWriter==0.9.3
xlwt==1.3.0
zipp==3.10.0
```

**Comment by YannickLevadoux** [comment]
Thank you @robinkeunen 

From the odoo:12.0 docker image, you need to install 

openupgradelib==3.4.0
psycopg2-binary==2.8.6

And it works !! Menu 'Edit Price' is available from Sale or Purchase menu and doing what it is supposed to do.


FYI, psycopg2-binary & psycopg2 looks not available in the docker container with the version you mentionned above. see below : 

```
 odoo@container:/$ pip3 install psycopg2==2.9.6
Collecting psycopg2==2.9.6
  Could not find a version that satisfies the requirement psycopg2==2.9.6 (from versions: 2.0.10, 2.0.11, 2.0.12, 2.0.13, 2.0.14, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.3.2, 2.4, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.5, 2.5.1, 2.5.2, 2.5.3, 2.5.4, 2.5.5, 2.6, 2.6.1, 2.6.2, 2.7, 2.7.1, 2.7.2, 2.7.3, 2.7.3.1, 2.7.3.2, 2.7.4, 2.7.5, 2.7.6, 2.7.6.1, 2.7.7, 2.8, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.8.5, 2.8.6)
No matching distribution found for psycopg2==2.9.6
odoo@container:/$ pip3 install psycopg2-binary==2.9.4
Collecting psycopg2-binary==2.9.4
  Could not find a version that satisfies the requirement psycopg2-binary==2.9.4 (from versions: 2.7.3.2, 2.7.4, 2.7.5, 2.7.6, 2.7.6.1, 2.7.7, 2.8, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.8.5, 2.8.6)
No matching distribution found for psycopg2-binary==2.9.4
```
I did not investigate more because it's actually working out !

**Comment by robinkeunen** [comment]
Great news :-)

We do not user Docker so I'm closing.
